[package]
name = "http_request"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
b3_utils = { workspace = true, features = ["logging", "stable_memory"] }
