[package]
name = "http_payment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_utils = { workspace = true, features = ["ledger"] }
candid = { workspace = true }
ic-cdk = { workspace = true }
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
